{
 "title": "Istio Mesh Dashboard",
 "description": "Istio Mesh Dashboard version 1.28.4",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Global Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic Volume",
   "type": "stat",
   "description": "Total requests in the cluster",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{namespace=\"devops-test\"}[1m]))"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "stat",
   "description": "Total success rate of requests in the cluster",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(istio_requests_total{namespace=\"devops-test\",response_code!~\"5..\"}[1m]))\n  /\n  sum(rate(istio_requests_total{namespace=\"devops-test\"}[1m]))\n) * 100"
    }
   ]
  },
  {
   "title": "4xxs",
   "type": "stat",
   "description": "Total 4xx requests in in the cluster",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum (rate(istio_requests_total{reporter=~\"source|waypoint\",response_code=~\"4..\"}[$__rate_interval])), 0.01)or vector(0)"
    }
   ]
  },
  {
   "title": "5xxs",
   "type": "stat",
   "description": "Total 5xx requests in in the cluster",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum (rate(istio_requests_total{reporter=~\"source|waypoint\",response_code=~\"5..\"}[$__rate_interval])), 0.01)or vector(0)"
    }
   ]
  },
  { "title": "Istio Component Versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Request rate per service",
   "type": "timeseries",
   "description": "Version number of each running instance",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total[1m])) by (destination_service)",
     "legendFormat": "{{component}} ({{tag}})"
    }
   ]
  },
  {
   "title": "Per pod Traffic",
   "type": "timeseries",
   "description": "Version number of each running instance",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{namespace=\"devops-test\"}[1m])) by (pod)",
     "legendFormat": "{{component}} ({{tag}})"
    }
   ]
  }
 ]
}